### ISSUE TITLE
Something that's not about code

### ISSUE THREAD

**Issue by Jetkun** [8ctopus/legendofrandom#2]
Hello, 8ctopus:
I don't know if you know the hacker destroyer2009, but I'm asking you here because I'm curious about his relationship with you. Because he hacked into the pro's computer at the APEX North American regional finals a few days ago and left his signature with yours. Through Google, I found a reverse learning site called R4ndom that you started more than a decade ago, so I ventured to ask. XD
https://www.youtube.com/watch?v=WMWmjJB0HtI
![_20240319203242](https://github.com/8ctopus/legendofrandom/assets/83955806/56fd8554-a4c5-4fba-8b3e-1db53149e80a)

**Comment by 8ctopus** [comment]
hello Jetkun, I don't know any of those guys. The legend of random website is not mine, it's just a great resource that I'm maintaining to avoid it to get lost.

**Comment by Jetkun** [comment]
got it,so sorry to bother you.
